# Generated by Django 4.2.6 on 2023-10-31 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='words',
            name='english',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='words',
            name='ukrainian',
            field=models.TextField(null=True),
        ),
    ]
