# Generated by Django 4.2.6 on 2023-11-03 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synonyms', '0001_initial'),
        ('words', '0003_words_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='words',
            name='synonyms',
            field=models.ManyToManyField(to='synonyms.synonyms'),
        ),
    ]
